root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main.exe ./cmd/server"
  bin = "./tmp/main.exe"
  delay = 0
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor", ".github",".git",".vscode"]

[log]
  time = true

[screen]
  clear_on_rebuild = true

[proxy]
  enabled = false
